version: "3.7"

services:
  pypi:
    image: docker.io/pypiserver/pypiserver:v1.5.1
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8080"
    volumes:
      - ./authfile:/data/.htpasswd
      - ./packages:/data/packages
    command: -a update,download,list -P /data/.htpasswd /data/packages
    restart: always
